# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num" #pagination generated sub path format
#pygments: true #for support {% highlight %}
#highlighter: pygments
markdown: kramdown #use kramdown to parse markdown
kramdown:
    input: GFM
    toc_levels: 2..4
    auto_ids: true
    auto_id_prefix: 'id-'
gems: [jekyll-paginate]
encoding: utf-8

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "32kb Tech Space"

description: "32kb Tech Space, share technology post"
author:
  name: 32kb
  email: 
  github: 32kb
  twitter: 32kb
  pinterest: 32kb
  linkedin: 32kb
  bio: Do not build on quicksand high
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: rss.xml
categories_path: category.html
tags_path: tag.html

BASE_PATH: 
